# Generated by Django 4.0.6 on 2022-07-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0003_icontactform_delete_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IContactForm',
            new_name='ContactForm',
        ),
    ]
