# Generated by Django 4.0.6 on 2022-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0004_rename_icontactform_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='is_send_copy_enabled',
            field=models.BooleanField(blank=True),
        ),
    ]
