# Generated by Django 4.0.6 on 2022-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0005_alter_contactform_is_send_copy_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='is_send_copy_enabled',
            field=models.BooleanField(null=True),
        ),
    ]
