# Generated by Django 4.0.6 on 2022-07-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0006_alter_contactform_is_send_copy_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='is_send_copy_enabled',
            new_name='isSendCopyEnabled',
        ),
    ]
