import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Modal from "../components/Modal";
import { IManProduct, IWomanProduct } from "../types/types";
import { getMenProducts, getWomenProducts } from "../helpers/api";

const Home: NextPage = () => {
    const [menProducts, setMenProducts] = useState<IManProduct[] | undefined>();
    const [womenProducts, setWomenProducts] = useState<
        IWomanProduct[] | undefined
    >();
    const [showModal, setShowModal] = useState(false);

    async function getProducts() {
        const menProducts = await getMenProducts();
        const womenProducts = await getWomenProducts();

        setMenProducts(menProducts);
        setWomenProducts(womenProducts);
    }

    function handle() {
        setShowModal(true);
    }

    // If page is refreshed we calling API to fetch products from backend.
    useEffect(() => {
        // menProducts array must be empty otherwise we will call for always.
        if (!menProducts) {
            getProducts();
        }
    });

    return (
        <div>
            <Head>
                <title>Golden Shoe: Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className="bg-black h-10 flex items-center justify-center text-sm font-medium text-white px-4 sm:px-6 lg:px-8">
                Get free delivery on orders over £100
            </p>

            <Modal show={showModal} />
            <div className="relative bg-white overflow-hidden">
                <div className="max-w-7xl mx-auto">
                    <div className="relative z-10 pb-8 sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32">
                        <main className="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
                            <div className="sm:text-center lg:text-left">
                                <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
                                    <span className="block xl:inline">
                                        Your online store of{" "}
                                    </span>
                                    <span className="block text-[#d77973] xl:inline">
                                        high-quality{" "}
                                    </span>
                                    <span className="block xl:inline">
                                        and{" "}
                                    </span>
                                    <span className="block text-[#d77973] xl:inline">
                                        affordable{" "}
                                    </span>
                                    <span className="block xl:inline">
                                        shoes
                                    </span>
                                </h1>
                                <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
                                    Find your perfect pair of shoes here in all
                                    shapes & sizes | Free shipping* & returns at
                                    Golden Shoe Zomersale: save up to 70% on
                                    even more looks from your favorite brands
                                </p>
                                <button onClick={handle}>FFFFFFFFFFFFF</button>
                                <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
                                    <div className="rounded-md shadow">
                                        <a
                                            href="#men"
                                            className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-[#d5785a] hover:bg-[#fd6432] md:py-4 md:text-lg md:px-10"
                                        >
                                            {" "}
                                            Men shoes{" "}
                                        </a>
                                    </div>
                                    <div className="mt-3 sm:mt-0 sm:ml-3">
                                        <a
                                            href="#women"
                                            className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-[#d5785a] hover:bg-[#fd6432] md:py-4 md:text-lg md:px-10"
                                        >
                                            {" "}
                                            Women shoes{" "}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </main>
                    </div>
                </div>
                <div className="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
                    <img
                        className="h-56 w-full object-contain sm:h-72 md:h-96 lg:w-full lg:h-full"
                        src="https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/72f16fba-27bf-4c6b-9bd6-f0f23e785137/custom-nike-metcon-8-by-you.png"
                        alt="Golden Nike"
                    />
                </div>
            </div>

            {/* PRODUCTS */}
            <div className="bg-white">
                <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
                    <h2 className="sr-only">Products</h2>

                    {/* MEN SHOES*/}
                    <br />
                    <h2
                        id="men"
                        className="text-2xl font-extrabold tracking-tight text-gray-900"
                    >
                        Men
                    </h2>
                    <br />
                    {menProducts ? (
                        <div className="grid grid-cols-1 gap-y-10 sm:grid-cols-2 gap-x-6 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                            {menProducts.map((product) => (
                                <a
                                    key={product.product.pid}
                                    href={product.product.href}
                                    className="group"
                                >
                                    <div className="w-full aspect-w-1 aspect-h-1 bg-gray-200 rounded-lg overflow-hidden xl:aspect-w-7 xl:aspect-h-8">
                                        <img
                                            src={
                                                product.product.colors[0]
                                                    .imageSrc
                                            }
                                            alt={
                                                product.product.colors[0]
                                                    .imageAlt
                                            }
                                            className="w-full h-full object-center object-cover group-hover:opacity-75"
                                        />
                                    </div>
                                    <h3 className="mt-4 text-sm text-gray-700">
                                        {product.product.name}
                                    </h3>
                                    <p className="mt-1 text-lg font-medium text-gray-900">
                                        {product.product.price}
                                    </p>
                                </a>
                            ))}
                        </div>
                    ) : (
                        <div>Loading...</div>
                    )}

                    {/* WOMEN SHOES*/}
                    <br />
                    <br />
                    <br />
                    <br />
                    <h2
                        id="women"
                        className="text-2xl font-extrabold tracking-tight text-gray-900"
                    >
                        Women
                    </h2>
                    <br />
                    {womenProducts ? (
                        <div className="grid grid-cols-1 gap-y-10 sm:grid-cols-2 gap-x-6 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                            {womenProducts.map((product) => (
                                <a
                                    key={product.product.pid}
                                    href={product.product.href}
                                    className="group"
                                >
                                    <div className="w-full aspect-w-1 aspect-h-1 bg-gray-200 rounded-lg overflow-hidden xl:aspect-w-7 xl:aspect-h-8">
                                        <img
                                            src={
                                                product.product.colors[0]
                                                    .imageSrc
                                            }
                                            alt={
                                                product.product.colors[0]
                                                    .imageAlt
                                            }
                                            className="w-full h-full object-center object-cover group-hover:opacity-75"
                                        />
                                    </div>
                                    <h3 className="mt-4 text-sm text-gray-700">
                                        {product.product.name}
                                    </h3>
                                    <p className="mt-1 text-lg font-medium text-gray-900">
                                        {product.product.price}
                                    </p>
                                </a>
                            ))}
                        </div>
                    ) : (
                        <div>Loading...</div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default Home;
