import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState, Fragment } from "react";
import { IManProduct, IWomanProduct } from "../types/types";
import { getMenProducts, getWomenProducts } from "../helpers/api";

import { Dialog, RadioGroup, Transition } from "@headlessui/react";
import { XIcon } from "@heroicons/react/outline";
import { StarIcon } from "@heroicons/react/solid";

const product = {
    name: "Basic Tee 6-Pack ",
    price: "$192",
    rating: 3.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
        "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    colors: [
        {
            name: "White",
            imgSrc: "",
            class: "bg-white",
            selectedClass: "ring-gray-400",
        },
        {
            name: "Gray",
            imgSrc: "",
            class: "bg-gray-200",
            selectedClass: "ring-gray-400",
        },
        {
            name: "Black",
            imgSrc: "",
            class: "bg-gray-900",
            selectedClass: "ring-gray-900",
        },
    ],
    sizes: [
        { name: "XXS", inStock: true },
        { name: "XS", inStock: true },
        { name: "S", inStock: true },
        { name: "M", inStock: true },
        { name: "L", inStock: true },
        { name: "XL", inStock: true },
        { name: "XXL", inStock: true },
        { name: "XXXL", inStock: false },
    ],
};

function classNames(...classes: any[]) {
    return classes.filter(Boolean).join(" ");
}

const Home: NextPage = () => {
    const [menProducts, setMenProducts] = useState<IManProduct[] | undefined>();
    const [womenProducts, setWomenProducts] = useState<
        IWomanProduct[] | undefined
    >();
    const [showModal, setShowModal] = useState<boolean>(false);
    const [selectedColor, setSelectedColor] = useState(product.colors[0]);
    const [selectedSize, setSelectedSize] = useState(product.sizes[2]);
    const [pid, setPid] = useState<number>();
    const [cart, setCart] = useState<number>();

    async function getProducts() {
        const menProducts = await getMenProducts();
        const womenProducts = await getWomenProducts();

        setMenProducts(menProducts);
        setWomenProducts(womenProducts);
    }

    // If page is refreshed we calling API to fetch products from backend.
    useEffect(() => {
        // menProducts array must be empty otherwise we will call for always.
        if (!menProducts) {
            getProducts();
        }
    });

    return (
        <div>
            <Head>
                <title>Golden Shoe: Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className="bg-black h-10 flex items-center justify-center text-sm font-medium text-white px-4 sm:px-6 lg:px-8">
                Get free delivery on orders over £100
            </p>

            <div className="relative bg-[#f6f6f6] overflow-hidden">
                <div className="max-w-7xl mx-auto">
                    <div className="relative z-10 pb-8 sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32">
                        <main className="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
                            <div className="sm:text-center lg:text-left">
                                <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
                                    <span className="block xl:inline">
                                        Your online store of{" "}
                                    </span>
                                    <span className="block text-[#d77973] xl:inline">
                                        high-quality{" "}
                                    </span>
                                    <span className="block xl:inline">
                                        and{" "}
                                    </span>
                                    <span className="block text-[#d77973] xl:inline">
                                        affordable{" "}
                                    </span>
                                    <span className="block xl:inline">
                                        shoes
                                    </span>
                                </h1>
                                <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
                                    Find your perfect pair of shoes here in all
                                    shapes & sizes | Free shipping* & returns at
                                    Golden Shoe Zomersale: save up to 70% on
                                    even more looks from your favorite brands
                                </p>
                                <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
                                    <div className="rounded-md shadow">
                                        <a
                                            href="#men"
                                            className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-[#d5785a] hover:bg-[#fd6432] md:py-4 md:text-lg md:px-10"
                                        >
                                            {" "}
                                            Men shoes{" "}
                                        </a>
                                    </div>
                                    <div className="mt-3 sm:mt-0 sm:ml-3">
                                        <a
                                            href="#women"
                                            className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-[#d5785a] hover:bg-[#fd6432] md:py-4 md:text-lg md:px-10"
                                        >
                                            {" "}
                                            Women shoes{" "}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </main>
                    </div>
                </div>
                <div className="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
                    <img
                        className="h-56 w-full object-contain sm:h-72 md:h-96 lg:w-full lg:h-full"
                        src="https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/72f16fba-27bf-4c6b-9bd6-f0f23e785137/custom-nike-metcon-8-by-you.png"
                        alt="Golden Nike"
                    />
                </div>
            </div>

            {/* PRODUCTS */}
            <div className="bg-white">
                <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
                    <h2 className="sr-only">Products</h2>

                    {/* MEN SHOES*/}
                    <br />
                    <h2
                        id="men"
                        className="text-2xl font-extrabold tracking-tight text-gray-900"
                    >
                        Men
                    </h2>
                    <br />
                    {menProducts ? (
                        <div className="grid grid-cols-1 gap-y-10 sm:grid-cols-2 gap-x-6 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                            {menProducts.map((product) => (
                                <a
                                    key={product.product.pid}
                                    href={product.product.href}
                                    className="group"
                                    type="button"
                                    onClick={() => setShowModal(true)}
                                >
                                    <div className="w-full aspect-w-1 aspect-h-1 bg-gray-200 rounded-lg overflow-hidden xl:aspect-w-7 xl:aspect-h-8">
                                        <img
                                            src={
                                                product.product.colors[0]
                                                    .imageSrc
                                            }
                                            alt={
                                                product.product.colors[0]
                                                    .imageAlt
                                            }
                                            className="w-full h-full object-center object-cover group-hover:opacity-75"
                                        />
                                    </div>
                                    <h3 className="mt-4 text-sm text-gray-700">
                                        {product.product.name}
                                    </h3>
                                    <p className="mt-1 text-lg font-medium text-gray-900">
                                        {product.product.price}
                                    </p>
                                </a>
                            ))}
                        </div>
                    ) : (
                        <div>Loading...</div>
                    )}

                    {/* WOMEN SHOES*/}
                    <br />
                    <br />
                    <br />
                    <br />
                    <h2
                        id="women"
                        className="text-2xl font-extrabold tracking-tight text-gray-900"
                    >
                        Women
                    </h2>
                    <br />
                    {womenProducts ? (
                        <div className="grid grid-cols-1 gap-y-10 sm:grid-cols-2 gap-x-6 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                            {womenProducts.map((product) => (
                                <a
                                    key={product.product.pid}
                                    href={product.product.href}
                                    className="group"
                                >
                                    <div className="w-full aspect-w-1 aspect-h-1 bg-gray-200 rounded-lg overflow-hidden xl:aspect-w-7 xl:aspect-h-8">
                                        <img
                                            src={
                                                product.product.colors[0]
                                                    .imageSrc
                                            }
                                            alt={
                                                product.product.colors[0]
                                                    .imageAlt
                                            }
                                            className="w-full h-full object-center object-cover group-hover:opacity-75"
                                        />
                                    </div>
                                    <h3 className="mt-4 text-sm text-gray-700">
                                        {product.product.name}
                                    </h3>
                                    <p className="mt-1 text-lg font-medium text-gray-900">
                                        {product.product.price}
                                    </p>
                                </a>
                            ))}
                        </div>
                    ) : (
                        <div>Loading...</div>
                    )}
                </div>
            </div>

            {/* SHOW MODAL */}
            {showModal ? (
                <Transition.Root show={showModal} as={Fragment}>
                    <Dialog
                        as="div"
                        className="relative z-10"
                        onClose={setShowModal}
                    >
                        <Transition.Child
                            as={Fragment}
                            enter="ease-out duration-300"
                            enterFrom="opacity-0"
                            enterTo="opacity-100"
                            leave="ease-in duration-200"
                            leaveFrom="opacity-100"
                            leaveTo="opacity-0"
                        >
                            <div className="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity md:block" />
                        </Transition.Child>

                        <div className="fixed z-10 inset-0 overflow-y-auto">
                            <div className="flex items-stretch md:items-center justify-center min-h-full text-center md:px-2 lg:px-4">
                                <Transition.Child
                                    as={Fragment}
                                    enter="ease-out duration-300"
                                    enterFrom="opacity-0 translate-y-4 md:translate-y-0 md:scale-95"
                                    enterTo="opacity-100 translate-y-0 md:scale-100"
                                    leave="ease-in duration-200"
                                    leaveFrom="opacity-100 translate-y-0 md:scale-100"
                                    leaveTo="opacity-0 translate-y-4 md:translate-y-0 md:scale-95"
                                >
                                    <Dialog.Panel className="flex text-base text-left transform transition w-full md:max-w-2xl md:px-4 md:my-8 lg:max-w-4xl">
                                        <div className="w-full relative flex items-center bg-white px-4 pt-14 pb-8 overflow-hidden shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
                                            <button
                                                type="button"
                                                className="absolute top-4 right-4 text-gray-400 hover:text-gray-500 sm:top-8 sm:right-6 md:top-6 md:right-6 lg:top-8 lg:right-8"
                                                onClick={() =>
                                                    setShowModal(false)
                                                }
                                            >
                                                <span className="sr-only">
                                                    Close
                                                </span>
                                                <XIcon
                                                    className="h-6 w-6"
                                                    aria-hidden="true"
                                                />
                                            </button>

                                            <div className="w-full grid grid-cols-1 gap-y-8 gap-x-6 items-start sm:grid-cols-12 lg:gap-x-8">
                                                <div className="aspect-w-2 aspect-h-3 rounded-lg bg-gray-100 overflow-hidden sm:col-span-4 lg:col-span-5">
                                                    <img
                                                        src={product.imageSrc}
                                                        alt={product.imageAlt}
                                                        className="object-center object-cover"
                                                    />
                                                </div>
                                                <div className="sm:col-span-8 lg:col-span-7">
                                                    <h2 className="text-2xl font-extrabold text-gray-900 sm:pr-12">
                                                        {product.name}
                                                    </h2>

                                                    <section
                                                        aria-labelledby="information-heading"
                                                        className="mt-2"
                                                    >
                                                        <h3
                                                            id="information-heading"
                                                            className="sr-only"
                                                        >
                                                            Product information
                                                        </h3>

                                                        <p className="text-2xl text-gray-900">
                                                            {product.price}
                                                        </p>

                                                        {/* Reviews */}
                                                        <div className="mt-6">
                                                            <h4 className="sr-only">
                                                                Reviews
                                                            </h4>
                                                            <div className="flex items-center">
                                                                <div className="flex items-center">
                                                                    {[
                                                                        0, 1, 2,
                                                                        3, 4,
                                                                    ].map(
                                                                        (
                                                                            rating
                                                                        ) => (
                                                                            <StarIcon
                                                                                key={
                                                                                    rating
                                                                                }
                                                                                className={classNames(
                                                                                    product.rating >
                                                                                        rating
                                                                                        ? "text-gray-900"
                                                                                        : "text-gray-200",
                                                                                    "h-5 w-5 flex-shrink-0"
                                                                                )}
                                                                                aria-hidden="true"
                                                                            />
                                                                        )
                                                                    )}
                                                                </div>
                                                                <p className="sr-only">
                                                                    {
                                                                        product.rating
                                                                    }{" "}
                                                                    out of 5
                                                                    stars
                                                                </p>
                                                                <a
                                                                    href="#"
                                                                    className="ml-3 text-sm font-medium text-indigo-600 hover:text-indigo-500"
                                                                >
                                                                    {
                                                                        product.reviewCount
                                                                    }{" "}
                                                                    reviews
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </section>

                                                    <section
                                                        aria-labelledby="options-heading"
                                                        className="mt-10"
                                                    >
                                                        <h3
                                                            id="options-heading"
                                                            className="sr-only"
                                                        >
                                                            Product options
                                                        </h3>

                                                        <form>
                                                            {/* Colors */}
                                                            <div>
                                                                <h4 className="text-sm text-gray-900 font-medium">
                                                                    Color
                                                                </h4>

                                                                <RadioGroup
                                                                    value={
                                                                        selectedColor
                                                                    }
                                                                    onChange={
                                                                        setSelectedColor
                                                                    }
                                                                    className="mt-4"
                                                                >
                                                                    <RadioGroup.Label className="sr-only">
                                                                        Choose a
                                                                        color
                                                                    </RadioGroup.Label>
                                                                    <span className="flex items-center space-x-3">
                                                                        {product.colors.map(
                                                                            (
                                                                                color
                                                                            ) => (
                                                                                <RadioGroup.Option
                                                                                    key={
                                                                                        color.name
                                                                                    }
                                                                                    value={
                                                                                        color
                                                                                    }
                                                                                    className={({
                                                                                        active,
                                                                                        checked,
                                                                                    }) =>
                                                                                        classNames(
                                                                                            color.selectedClass,
                                                                                            active &&
                                                                                                checked
                                                                                                ? "ring ring-offset-1"
                                                                                                : "",
                                                                                            !active &&
                                                                                                checked
                                                                                                ? "ring-2"
                                                                                                : "",
                                                                                            "-m-0.5 relative p-0.5 rounded-full flex items-center justify-center cursor-pointer focus:outline-none"
                                                                                        )
                                                                                    }
                                                                                >
                                                                                    <RadioGroup.Label
                                                                                        as="span"
                                                                                        className="sr-only"
                                                                                    >
                                                                                        {
                                                                                            color.name
                                                                                        }
                                                                                    </RadioGroup.Label>
                                                                                    <span
                                                                                        aria-hidden="true"
                                                                                        className={classNames(
                                                                                            color.class,
                                                                                            "h-8 w-8 border border-black border-opacity-10 rounded-full"
                                                                                        )}
                                                                                    />
                                                                                </RadioGroup.Option>
                                                                            )
                                                                        )}
                                                                    </span>
                                                                </RadioGroup>
                                                            </div>

                                                            {/* Sizes */}
                                                            <div className="mt-10">
                                                                <div className="flex items-center justify-between">
                                                                    <h4 className="text-sm text-gray-900 font-medium">
                                                                        Size
                                                                    </h4>
                                                                    <a
                                                                        href="#"
                                                                        className="text-sm font-medium text-indigo-600 hover:text-indigo-500"
                                                                    >
                                                                        Size
                                                                        guide
                                                                    </a>
                                                                </div>

                                                                <RadioGroup
                                                                    value={
                                                                        selectedSize
                                                                    }
                                                                    onChange={
                                                                        setSelectedSize
                                                                    }
                                                                    className="mt-4"
                                                                >
                                                                    <RadioGroup.Label className="sr-only">
                                                                        Choose a
                                                                        size
                                                                    </RadioGroup.Label>
                                                                    <div className="grid grid-cols-4 gap-4">
                                                                        {product.sizes.map(
                                                                            (
                                                                                size
                                                                            ) => (
                                                                                <RadioGroup.Option
                                                                                    key={
                                                                                        size.name
                                                                                    }
                                                                                    value={
                                                                                        size
                                                                                    }
                                                                                    disabled={
                                                                                        !size.inStock
                                                                                    }
                                                                                    className={({
                                                                                        active,
                                                                                    }) =>
                                                                                        classNames(
                                                                                            size.inStock
                                                                                                ? "bg-white shadow-sm text-gray-900 cursor-pointer"
                                                                                                : "bg-gray-50 text-gray-200 cursor-not-allowed",
                                                                                            active
                                                                                                ? "ring-2 ring-indigo-500"
                                                                                                : "",
                                                                                            "group relative border rounded-md py-3 px-4 flex items-center justify-center text-sm font-medium uppercase hover:bg-gray-50 focus:outline-none sm:flex-1"
                                                                                        )
                                                                                    }
                                                                                >
                                                                                    {({
                                                                                        active,
                                                                                        checked,
                                                                                    }) => (
                                                                                        <>
                                                                                            <RadioGroup.Label as="span">
                                                                                                {
                                                                                                    size.name
                                                                                                }
                                                                                            </RadioGroup.Label>
                                                                                            {size.inStock ? (
                                                                                                <span
                                                                                                    className={classNames(
                                                                                                        active
                                                                                                            ? "border"
                                                                                                            : "border-2",
                                                                                                        checked
                                                                                                            ? "border-indigo-500"
                                                                                                            : "border-transparent",
                                                                                                        "absolute -inset-px rounded-md pointer-events-none"
                                                                                                    )}
                                                                                                    aria-hidden="true"
                                                                                                />
                                                                                            ) : (
                                                                                                <span
                                                                                                    aria-hidden="true"
                                                                                                    className="absolute -inset-px rounded-md border-2 border-gray-200 pointer-events-none"
                                                                                                >
                                                                                                    <svg
                                                                                                        className="absolute inset-0 w-full h-full text-gray-200 stroke-2"
                                                                                                        viewBox="0 0 100 100"
                                                                                                        preserveAspectRatio="none"
                                                                                                        stroke="currentColor"
                                                                                                    >
                                                                                                        <line
                                                                                                            x1={
                                                                                                                0
                                                                                                            }
                                                                                                            y1={
                                                                                                                100
                                                                                                            }
                                                                                                            x2={
                                                                                                                100
                                                                                                            }
                                                                                                            y2={
                                                                                                                0
                                                                                                            }
                                                                                                            vectorEffect="non-scaling-stroke"
                                                                                                        />
                                                                                                    </svg>
                                                                                                </span>
                                                                                            )}
                                                                                        </>
                                                                                    )}
                                                                                </RadioGroup.Option>
                                                                            )
                                                                        )}
                                                                    </div>
                                                                </RadioGroup>
                                                            </div>

                                                            <button
                                                                type="submit"
                                                                className="mt-6 w-full bg-indigo-600 border border-transparent rounded-md py-3 px-8 flex items-center justify-center text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                                                            >
                                                                Add to bag
                                                            </button>
                                                        </form>
                                                    </section>
                                                </div>
                                            </div>
                                        </div>
                                    </Dialog.Panel>
                                </Transition.Child>
                            </div>
                        </div>
                    </Dialog>
                </Transition.Root>
            ) : null}
        </div>
    );
};

export default Home;
